using System.Collections.Generic;
using BepInEx;
using Jotunn.Entities;
using Jotunn.Managers;
using UnityEngine;

namespace RtDLegends                        
{
    internal partial class RtDLegends : BaseUnityPlugin   
    {
        private CustomLocalization Localization;
        
        public void JSONSupport()
        {
            TextAsset[] textAssets = _myAssets.LoadAllAssets<TextAsset>();
            foreach (var textAsset in textAssets)
            {
                var lang = textAsset.name.Replace("_RtDLegends.json", null);
                Localization.AddJsonFile(lang, textAsset.ToString());
            }
        }
        
        public void Addlocalizations()
        {
            Localization = LocalizationManager.Instance.GetLocalization();
            Localization.AddTranslation("English", new Dictionary<string, string>
            {
                { "AshLandsRock3_RtD", "Charred Rock" },
                { "AshLandsRock3_desc_RtD", "Whatever heat did this was not natural. The stone remembers it." },
                { "DeepNorthRock3_RtD", "Arcane Rock" },
                { "DeepNorthRock3_desc_RtD", "Cold to the touch and humming faintly. The Deep North did not make this. Something else did." },
                { "FroMetalBar_RtD", "Arcane Bar" },
                { "FroMetalBar_desc_RtD", "It catches light that isn't there and holds it. Smelting it felt like being watched." },
                { "BurningGland_RtD", "Burning Gland" },
                { "BurningGland_desc_RtD", "A manifestation of pure spiritual energy that exists beyond the physical realm. It is said that with this, one may summon forth the Necromancer Queen." },
                { "Fader_RtD", "Dragon Lord" },
                { "DragonCore_RtD", "Dragon Core" },
                { "DragonCore_desc_RtD", "It radiates a heat that has nowhere to go. Weapons forged with it do not burn clean — they burn with something that does not go out." },
                { "DragonEgg_RtD", "Searing Dragon Egg" },
                { "DragonEgg_desc_RtD", "These eggs were cold once. Then the world began to burn, and the contempt inside them found a temperature it agreed with." },
                { "TrophyHatchling_RtD", "Hatchling Trophy" },
                { "TrophyHatchling_desc_RtD", "Small. Still dangerous. What it would have become is a question best left unanswered." },
                { "ArtisanTable_RtD", "Artisan Forge" },
                { "Assassin_RtD", "Undead Assassin" },
                { "Berserker_RtD", "Flesh Eater" },
                { "FallenCrusader_RtD", "Fallen Crusader" },
                { "Wizard_RtD", "Undead Wizard" },
                { "Necromancer_RtD", "Necromancer Queen" },
                { "Demon_RtD", "Demon" },
                { "DragonBoar_RtD", "Dragon Boar" },
                { "DragonBoar_RtD1", "Dragon Boar" },
                { "DragonPiglet_RtD", "Dragon Piglet" },
                { "DragonBoarMeat_RtD", "Raw Dragon Boar Meat" },
                { "CookedDragonBoarMeat_RtD", "Cooked Dragon Boar Meat" },
                { "DemonHide_RtD", "Demon Hide" },
                { "DemonHide_desc_RtD", "Scaled, jagged, and faintly warm. It resists the blade and the needle alike. Whatever wore this did not want to give it up." },
                { "CookedFaeWolfMeat_RtD", "Fae Wolf Meat" },
                { "CookedFaeWolfMeat_desc_RtD", "It tastes of something you cannot name. You feel it long after the meal is done." },
                { "FaeWolfMeat_RtD", "Raw FaeWolf Meat" },
                { "FaeWolfMeat_desc_RtD", "Handled carefully. The magic in it does not leave when the creature does." },
                { "FaeNectar_RtD", "Fae Nectar" },
                { "FaeNectar_desc_RtD", "The Fae do not share this willingly. What you hold was taken, and something knows it is gone." },
                { "FaeTrophyWolf_RtD", "FaeWolf Trophy" },
                { "FaeTrophyWolf_desc_RtD", "Proof of a kill the forest has not forgotten." },
                { "FaeWolfFang_RtD", "FaeWolf Fang" },
                { "FaeWolfFang_desc_RtD", "Taken from creatures that move between worlds without asking permission. The fang carries that same disregard for boundaries." },
                { "FaeWolfPelt_RtD", "FaeWolf Pelt" },
                { "FaeWolfPelt_desc_RtD", "The magic woven into it did not die with the wolf. It is waiting to see what you intend to do with it." },
                { "FairySilk_RtD", "Fae Silk" },
                { "FairySilk_desc_RtD", "Almost weightless. It shimmers with light it should not have. Wearing it feels like being seen by something very far away." },
                { "ElfHunterF_RtD", "Elf Hunter" },
                { "ElfHunterM_RtD", "Elf Hunter" },
                { "ElfPriestM_RtD", "Elf Priest" },
                { "ElfWarriorF_RtD", "Elf Warrior" },
                { "ElfWarriorM_RtD", "Elf Warrior" },
                { "FaeWolfIce_RtD", "FaeWolf" },
                { "FaeWolfIce_RtD1", "FaeWolf" },
                { "FaeWolfIceCub_RtD", "FaeWolf Cub" },
                { "FaeWolfLightening_RtD", "FaeWolf" },
                { "FaeWolfLightening_RtD1", "FaeWolf" },
                { "FaeWolfLighteningCub_RtD", "FaeWolf Cub" },
                { "Fairy1_RtD", "Fae Spirit" },
                { "Fairy2_RtD", "Fae Spirit" },
                { "Golem_RtD", "Elemental Golem" },
                { "FaeTree_RtD", "Magical Fae Tree" },
                { "Spirit_RtD", "Spirit of the Wood" },
                { "TrophySpirit_RtD", "Spirit Trophy" },
                { "TrophySpirit_desc_RtD", "It does not feel like a trophy. It feels like an accusation." },
                { "SpiritHeart_RtD", "Spirit Heart" },
                { "SpiritHeart_desc_RtD", "Still beating. You are not sure how. Used to forge Thor's Hammer — which may explain a great deal." },
                { "FaeSpawner_RtD", "Fae Spawner" },
                { "Vegvisir_Spirit_RtD", "Vegvisir" },
                { "Vegvisir_Spirit_register_RtD", "Forest Spirit" },
                { "SpiritShrineMap_RtD", "Spirit Shrine" },
                { "Vegvisir_Fader_RtD", "Vegvisir" },
                { "CrystalFormation5_RtD", "Shadow Crystal" },
                { "CrystalFormation6_RtD", "Shadow Crystal" },
                { "CrystalFormation7_RtD", "Shadow Crystal" },
                { "CrystalFormation8_RtD", "Shadow Crystal" },
                { "Vegvisir_Necromancer_RtD", "Vegvisir" },
                { "Vegvisir_Fader_register_RtD", "King of Dragons" },
                { "Vegvisir_Necromancer_register_RtD", "Necromancer Queen" },
                { "NecromancerAltarMap_RtD", "Necromancer" },


                { "ThorHammer_RtD", "Thor's Hammer" },
                { "ThorHammer_desc_RtD", "It chooses who lifts it. So far it has chosen you. Do not take that as a compliment." },
                { "DragonBoarRuinStone_RtD", "Chris P Bacon discovered this Rune Stone, then died within minutes from being eaten." },
                { "Vegvisir_Thor_RtD", "Vegvisir" },
                { "SpiritThorMap_RtD", "Thors Shrine" },
                { "Vegvisir_Thor_register_RtD", "The god of lightning" },

                { "CursedKnight_RtD", "Cursed Knight" },
                { "FroWood_RtD", "FroWood" },
                { "FroWood_desc_RtD", "Pale and silvery, cold to the touch even in summer. The frost in it predates the tree. The tree grew around it." },
                { "ArcaneOre_RtD", "Arcane Ore" },
                { "ArcaneOre_desc_RtD", "It resists the furnace until it decides not to. Do not rush it." },
                { "IceCrystal_RtD", "Icy Crystal" },
                { "IceCrystal_desc_RtD", "It captures the cold of the mountain and refuses to let go. Beautiful in the way only dangerous things are." },
                { "ShadowCrystal_RtD", "Shadow Crystal" },
                { "ShadowCrystal_desc_RtD", "It drinks the light around it. The longer you hold it, the less you feel like yourself." },
                { "CinderWood_RtD", "Cinder Wood" },
                { "CinderWood_desc_RtD", "Hollowed by fire but still standing. Still strong. Whatever burned through it decided to leave the strength behind." },
                { "LichKing_RtD", "The Lich Spirit" },
                { "DemonHorn_RtD", "Demon Horn" },
                { "DemonHorn_desc_RtD", "The essence of the creature still lives in it. Using it grants a fragment of that darkness. Whether you want it or not is beside the point." },
                { "SO_Thor_RtD", "Frostbringer" },
                { "Befouler_RtD", "Befouler of Ice" },
                { "Davil_RtD", "Frostflame Horror" },
                { "Executioner_RtD", "Icebound Betrayer" },
                { "NorthernTroll_RtD", "Blight Troll" },
                { "BlackForestGold_RtD", "Gold" },
                { "MeadowsFlint_RtD", "Flint" },
                { "MeadowsZinc_RtD", "Zinc" },
                { "PlainsBlackMetal_RtD", "BlackMetal" },
                { "MistlandsFelOre_RtD", "FelOre" },
                { "MountainOrichalcum_RtD", "Orichalcum" },
                { "PlainsBloodiron_RtD", "BloodIron" },
                { "SwampMooniron_RtD", "MoonIron" },
                { "Item_BloodironBar_RtD", "BloodIron" },
                { "Item_BloodironBar_desc_RtD", "Smelted from ore that runs red before it even touches the flame. It does not ask why." },
                { "Item_BloodironOre_RtD", "BloodIron Ore" },
                { "Item_BloodironOre_desc_RtD", "The colour is not rust. The Plains made sure of that." },
                { "Item_GoldBar_RtD", "Gold" },
                { "Item_GoldBar_desc_RtD", "It shines like something worth dying over. Many have confirmed this." },
                { "Item_GoldOre_RtD", "Gold Ore" },
                { "Item_GoldOre_desc_RtD", "Pulled from the dark. Worth more than what was spent getting it. Usually." },
                { "Item_MoonironBar_RtD", "MoonIron" },
                { "Item_MoonironBar_desc_RtD", "Cold light locked into metal. It glows faintly on moonless nights, as if looking for something." },
                { "Item_MoonironOre_RtD", "MoonIron Ore" },
                { "Item_MoonironOre_desc_RtD", "The Swamp gives up its ore reluctantly. This one carries the damp of wherever it came from." },
                { "Item_OrichalcumBar_RtD", "Orichalcum" },
                { "Item_OrichalcumBar_desc_RtD", "Old metal. Older than the Mountain's name. It remembers being something else." },
                { "Item_OrichalcumOre_RtD", "Orichalcum Ore" },
                { "Item_OrichalcumOre_desc_RtD", "Dense and strange. The Mountain does not offer this easily. You earned it or you stole it." },
                { "Item_ZincBar_RtD", "Zinc" },
                { "Item_ZincBar_desc_RtD", "Humble and reliable. The foundation of things that matter." },
                { "Item_ZincOre_RtD", "Zinc Ore" },
                { "Item_ZincOre_desc_RtD", "Common enough to overlook. Important enough not to." },
                { "Item_BrassBar_RtD", "Brass" },
                { "Item_BrassBar_desc_RtD", "Zinc and copper decided to become something neither of them was alone. The result is louder than both." },
                { "Item_BrightsteelBar_RtD", "BrightSteel" },
                { "Item_BrightsteelBar_desc_RtD", "It catches light from angles that make no sense. The Swamp forged something that does not belong there." },
                { "Item_CelestialBronzeBar_RtD", "Celestial Bronze" },
                { "Item_CelestialBronzeBar_desc_RtD", "Bronze that touched something it should not have on the way to being made. It crackles if you listen closely enough." },
                { "Item_NetheriteBar_RtD", "Netherite" },
                { "Item_NetheriteBar_desc_RtD", "Heavier than it looks. Darker than it should be. The void left something of itself in the smelting." },
                { "Item_QuicksilverBar_RtD", "QuickSilver" },
                { "Item_QuicksilverBar_desc_RtD", "It moves when you are not touching it. Just slightly. Just enough." },
                { "FelmetalBar_RtD", "Felmetal" },
                { "FelmetalBar_desc_RtD", "The Mistlands produced this. That alone should tell you something about what it is capable of." },
                { "FelmetalOre_RtD", "Felmetal Ore" },
                { "FelmetalOre_desc_RtD", "Cold to the touch in a way that has nothing to do with temperature. The mist is still in it." },
                { "SpiritEssense_RtD", "Spirit Essence" },
                { "SpiritEssense_desc_RtD", "What remains when a spirit is unmade. It should not exist in a jar. And yet here it is." },
                { "se_armorweakness_name", "Physical Weakness" },
                { "se_armorweakness_tooltip", "Your body is failing where it should not." },
                { "se_armorweakness_start", "The flesh is losing ground." },
                { "se_frosted_name", "Frost Weakness" },
                { "se_frosted_tooltip", "The cold has found a way in that it will not give back." },
                { "se_frosted_start", "Something in you is freezing." },
                { "se_shocked_name", "Electric Weakness" },
                { "se_shocked_tooltip", "Your nerves are no longer entirely yours." },
                { "se_shocked_start", "The lightning has left something behind." },
                { "se_weakened_name", "Poison Weakness" },
                { "se_weakened_tooltip", "The poison works slowly. That is the point." },
                { "se_weakened_start", "Something in the blood has turned." },
                { "EikthyrSpirit_RtD", "Eikthyr's Spirit" },
                { "MountainBoss_RtD", "Fenrir King" },
                { "PlainsBoss_RtD", "Goblin King" },
                { "SpiderQueen_RtD", "Spider Queen" },
                { "SwampBoss_RtD", "Undead Lord" },
                { "TrollKing_RtD", "Troll King" },
                { "PlainsChomper1_RtD", "Chomper" },
                { "PlainsChomper2_RtD", "Chomper" },
                { "PlainsChomper3_RtD", "Chomper" },
                { "PlainsChomper4_RtD", "Chomper" },
                { "BlackForestGolem_RtD", "Mossy Undead" },
                { "MeadowsGolem_RtD", "Forest Golem" },
                { "BlackForestLocMur_RtD", "Locmur" },
                { "MountainUndead_RtD", "Frozen Undead" },
                { "PlainsSizzler_RtD", "Sizzler" },
                { "SwampSludger_RtD", "Sludger" },
                { "MeadowsSnade_RtD", "Snade" },
                { "MistlandsSpider1_RtD", "Arachnid" },
                { "MistlandsSpider2_RtD", "Arachnid" },
                { "MistlandsSpider3_RtD", "Arachnid" },
                { "MistlandsSpider4_RtD", "Arachnid" },
                { "MountainWatcher_RtD", "Watcher" },
                { "BlackForestCore_RtD", "BlackForest Core" },
                { "BlackForestCore_desc_RtD", "The forest compressed into a single object. It is still watching." },
                { "MeadowsCore_RtD", "Meadows Core" },
                { "MeadowsCore_desc_RtD", "Warm and golden, like the Meadows before everything went wrong." },
                { "MistlandsCore_RtD", "Mistlands Core" },
                { "MistlandsCore_desc_RtD", "It shifts in your hand like it cannot decide what it is. The mist never could." },
                { "AshLandsCore_RtD", "AshLands Core" },
                { "AshLandsCore_desc_RtD", "Forged in a place where the ground itself is on fire. It has never cooled. It will not." },
                { "DeepNorthCore_RtD", "DeepNorth Core" },
                { "DeepNorthCore_desc_RtD", "It's so cold to the touch it almost burns, something wicked created this." },
                { "MountainCore_RtD", "Mountain Core" },
                { "MountainCore_desc_RtD", "Dense with cold and old fury. The Mountain gave this up only because something stronger took it." },
                { "PlainsCore_RtD", "Plains Core" },
                { "PlainsCore_desc_RtD", "Dark as the void the Plains border. Hold it too long and you start to feel the edge." },
                { "SwampCore_RtD", "Swamp Core" },
                { "SwampCore_desc_RtD", "Pulled from somewhere deep beneath the rot. It smells of things that have been dead long enough to become something else." },
                { "BlackForestToken_RtD", "BlackForest Token" },
                { "BlackForestToken_desc_RtD", "The forest accepts this as a debt. Present it at the altar and something old will answer." },
                { "MeadowsToken_RtD", "Meadows Token" },
                { "MeadowsToken_desc_RtD", "Small and ordinary looking. The power in it is neither." },
                { "MistlandsToken_RtD", "Mistlands Token" },
                { "MistlandsToken_desc_RtD", "The mist parted to let this be made. It will part again when you call what waits within." },
                { "AshLandsToken_RtD", "AshLands Token" },
                { "AshLandsToken_desc_RtD", "Seared at the edges. The Ashlands marks everything it touches." },
                { "DeepNorthToken_RtD", "DeepNorth Token" },
                { "DeepNorthToken_desc_RtD", "Cold as the place it came from. The magic inside it has been waiting longer than you have been alive." },
                { "MountainToken_RtD", "Mountain Token" },
                { "MountainToken_desc_RtD", "The peak does not give tokens. This was taken. Something noticed." },
                { "PlainsToken_RtD", "Plains Token" },
                { "PlainsToken_desc_RtD", "The void it carries is not empty. It is full of something that has no name yet." },
                { "SwampToken_RtD", "Swamp Token" },
                { "SwampToken_desc_RtD", "The bog does not forget who took this. Neither will what you summon with it." },
                { "Vegvisir_RtD", "Vegvisir" },
                { "BlackForestAltar_RtD", "Troll King" },
                { "MeadowsAltar_RtD", "Eikthyr Spirit" },
                { "MistlandsAltar_RtD", "Spider Queen" },
                { "MountainAltar_RtD", "Fenrir King" },
                { "PlainsAltar_RtD", "Goblin King" },
                { "SwampAltar_RtD", "Swamp Lord" },
                { "MeadowsHobgoblin_RtD", "Hobgoblin" },
                { "MeadowsKobald_RtD", "Kobald" },
                { "MeadowsSpider_RtD", "Spider" },
                { "BlacKForestTreeEnt_RtD", "Tree Ent" },
                { "BlacKForestTroll_RtD", "Troll" },
                { "BlackForestUndead_RtD", "Undead" },
                { "SwampGhoul_RtD", "Ghoul" },
                { "SwampMummy_RtD", "Mummy" },
                { "SwampRat_RtD", "Rat" },
                { "SwampVampire_RtD", "Vampire" },
                { "MountainGriffin_RtD", "Griffin" },
                { "MountainWerewolf_RtD", "Werewolf" },
                { "MountainWyvern_RtD", "Wyvern" },
                { "PlainsChimera_RtD", "Chimera" },
                { "PlainsDragonide_RtD", "Dragonide" },
                { "PlainsOrc_RtD", "Orc" },
                { "MistlandsHarpy_RtD", "Harpy" },
                { "MistlandsManticora_RtD", "Maticora" },
                { "MistlandsWolf_RtD", "Vile Wolf" },

                // Armor - AshLands
                { "AshLandsArcherCape_RtD", "<#00A866>Archer Ljósálfar Cloak" },
                { "AshLandsArcherCape_desc_RtD", "Lined with demon hide, light enough to draw and loose without a breath of resistance. The Ashlands teaches archers to move fast or not at all." },
                { "AshLandsArcherChest_RtD", "<#00A866>Archer Ljósálfar Chest" },
                { "AshLandsArcherChest_desc_RtD", "Hardened against the Ashlands heat without sacrificing the reach that keeps you alive out here." },
                { "AshLandsArcherHood_RtD", "<#00A866>Archer Ljósálfar Hood" },
                { "AshLandsArcherHood_desc_RtD", "Ash settles on everything in South Alfheimr. This hood was made so it settles on your enemies before they see you." },
                { "AshLandsArcherLegs_RtD", "<#00A866>Archer Ljósálfar Legguards" },
                { "AshLandsArcherLegs_desc_RtD", "Built for ground that scorches and shifts. An archer who cannot move is already dead." },
                { "AshLandsAssassinCape_RtD", "<#FF1313>Light Ljósálfar Cloak" },
                { "AshLandsAssassinCape_desc_RtD", "Thin enough to disappear in firelight. The assassins of South Alfheimr learned long ago that shadow is its own armor." },
                { "AshLandsAssassinChest_RtD", "<#BE0505>Assassin Ljósálfar Vest" },
                { "AshLandsAssassinChest_desc_RtD", "Cut close and treated dark. In the Ashlands, being seen is dying. This vest ensures you are not seen." },
                { "AshLandsAssassinHood_RtD", "<#BE0505>Assassin Ljósálfar Hood" },
                { "AshLandsAssassinHood_desc_RtD", "The face beneath is the last thing your target does not see coming." },
                { "AshLandsAssassinLegs_RtD", "<#BE0505>Assassin Ljósálfar Legs" },
                { "AshLandsAssassinLegs_desc_RtD", "Silent on ash, silent on stone. The Ashlands rewards those who move without announcement." },
                { "AshLandsHybridCape_RtD", "<#FF1313>Hybrid Ljósálfar Cloak" },
                { "AshLandsHybridCape_desc_RtD", "For those who refused to choose a single way of killing. The Ashlands respects that kind of commitment." },
                { "AshLandsMonkCape_RtD", "<#FF8645>Monk Ljósálfar Cloak" },
                { "AshLandsMonkCape_desc_RtD", "Odin's Monks in South Alfheimr do not pray for safety. They pray to be useful. The cloak reflects that arrangement." },
                { "AshLandsMonkChest_RtD", "<#FF8645>Monk Ljósálfar Robes" },
                { "AshLandsMonkChest_desc_RtD", "The fire does not touch these robes the same way it touches everything else. Something in the weave decided to hold." },
                { "AshLandsMonkHood_RtD", "<#FF8645>Monk Ljósálfar Hood" },
                { "AshLandsMonkHood_desc_RtD", "Worn in devotion and in fire. The Monks of Alfheimr learned that both are the same thing." },
                { "AshLandsMonkLegs_RtD", "<#FF8645>Monk Ljósálfar Legs" },
                { "AshLandsMonkLegs_desc_RtD", "Made to kneel on scorched ground without flinching. The flinching was trained out of them long before the legs were made." },
                { "AshLandsWarriorChest_RtD", "<#DCA44C>Warrior Ljósálfar Battleplate" },
                { "AshLandsWarriorChest_desc_RtD", "Forged to take punishment that would end lesser warriors. In South Alfheimr, the punishment always comes." },
                { "AshLandsWarriorHelmet_RtD", "<#DCA44C>Warrior Ljósálfar Helmet" },
                { "AshLandsWarriorHelmet_desc_RtD", "The visor narrows your world to what is directly ahead. In the Ashlands, that is enough." },
                { "AshLandsWarriorLegs_RtD", "<#DCA44C>Warrior Ljósálfar Greaves" },
                { "AshLandsWarriorLegs_desc_RtD", "Planted on burning ground and unmoved. That is what these greaves were made to accomplish." },

                // Armor - BlackForest
                { "BlackForestArcherChest_RtD", "<#00A866>Archer Forest Chest" },
                { "BlackForestArcherChest_desc_RtD", "The Black Forest does not forgive loud movement. This chest piece was made with that lesson already learned." },
                { "BlackForestArcherHelmet_RtD", "<#00A866>Archer Forest Helmet" },
                { "BlackForestArcherHelmet_desc_RtD", "The trees close in here. An archer who cannot see the gap between them does not survive the first night." },
                { "BlackForestArcherLegs_RtD", "<#00A866>Archer Forest Legguards" },
                { "BlackForestArcherLegs_desc_RtD", "Built for root and rock and the kind of dark that has things moving in it. Quick legs or no legs." },
                { "BlackForestHardLeatherCape_RtD", "Hard Leather Forest Cape" },
                { "BlackForestHardLeatherCape_desc_RtD", "Cured leather that has seen better forests. It holds together out of stubbornness more than craft." },
                { "BlackForestMonkCape_RtD", "<#FF8645>Monk Forest Cloak" },
                { "BlackForestMonkCape_desc_RtD", "Odin's Monks move through the Cursed Forest in silence. The cloak helps. The forest notices anyway." },
                { "BlackForestMonkChest_RtD", "<#FF8645>Monk Forest Robes" },
                { "BlackForestMonkChest_desc_RtD", "The roots reach toward these robes and then stop. Something in the weave reminds them to reconsider." },
                { "BlackForestMonkHood_RtD", "<#FF8645>Monk Forest Hood" },
                { "BlackForestMonkHood_desc_RtD", "Worn in a forest that watches. The hood does not make you invisible. It makes you look like you belong." },
                { "BlackForestMonkLegs_RtD", "<#FF8645>Monk Forest Pants" },
                { "BlackForestMonkLegs_desc_RtD", "Moving through cursed undergrowth in silence requires the right legs. These were made by someone who learned that the hard way." },

                // Armor - DeepNorth
                { "DeepNorthArcherChest_RtD", "<#00A866>Archer Fae Chest" },
                { "DeepNorthArcherChest_desc_RtD", "In North Alfheimr the cold makes fingers slow. This chest was crafted so the rest of you stays fast enough to compensate." },
                { "DeepNorthArcherHood_RtD", "<#00A866>Archer Fae Hood" },
                { "DeepNorthArcherHood_desc_RtD", "The wind in the Deep North carries ice and worse. This hood keeps your eyes clear and your aim honest." },
                { "DeepNorthArcherLegs_RtD", "<#00A866>Archer Fae Legguards" },
                { "DeepNorthArcherLegs_desc_RtD", "Arcane stitching keeps the frost from settling in the joints. What it cannot keep out is the feeling that something is watching you draw." },
                { "DeepNorthAssassinChest_RtD", "<#BE0505>Assassin Fae Chest" },
                { "DeepNorthAssassinChest_desc_RtD", "The Deep North rewards patience more than speed. This chest was made for those who know how to wait in the cold." },
                { "DeepNorthAssassinHood_RtD", "<#BE0505>Assassin Fae Hood" },
                { "DeepNorthAssassinHood_desc_RtD", "The pale light of North Alfheimr makes shadows rare. This hood was crafted to make the most of the few there are." },
                { "DeepNorthAssassinLegs_RtD", "<#BE0505>Assassin Fae Trousers" },
                { "DeepNorthAssassinLegs_desc_RtD", "Silent on frozen ground. The arcane thread in the hem muffles the crunch that would otherwise announce you." },
                { "DeepNorthHybridCape_RtD", "Hybrid Fae Cloak" },
                { "DeepNorthHybridCape_desc_RtD", "The Deep North does not care how you survive it. Only that you do." },
                { "DeepNorthMonkCape_RtD", "<#FF8645>Monk Fae Cloak" },
                { "DeepNorthMonkCape_desc_RtD", "Odin's Monks come to North Alfheimr to understand what endures. The cold teaches that lesson without words." },
                { "DeepNorthMonkChest_RtD", "<#FF8645>Monk Fae Robes" },
                { "DeepNorthMonkChest_desc_RtD", "Woven with arcane intent. The magic in these robes is old enough to remember when North Alfheimr was something else." },
                { "DeepNorthMonkHood_RtD", "<#FF8645>Monk Fae Hood" },
                { "DeepNorthMonkHood_desc_RtD", "Worn in a place where the sky offers no comfort. The hood reminds you that comfort was never the point." },
                { "DeepNorthMonkLegs_RtD", "<#FF8645>Monk Fae Leggings" },
                { "DeepNorthMonkLegs_desc_RtD", "The cold that lives in the Deep North gets into everything eventually. These leggings slow it down just enough to matter." },
                { "DeepNorthWarriorChest_RtD", "<#DCA44C>Warrior Fae Chest" },
                { "DeepNorthWarriorChest_desc_RtD", "Built for a cold that does not negotiate. Warriors of North Alfheimr wear this and face what the dark sends." },
                { "DeepNorthWarriorHelmet_RtD", "<#DCA44C>Warrior Fae Helmet" },
                { "DeepNorthWarriorHelmet_desc_RtD", "Arcane runes line the inside. They do not keep you warm. They keep you awake, which in the Deep North is more important." },
                { "DeepNorthWarriorLegs_RtD", "<#DCA44C>Warrior Fae Greaves" },
                { "DeepNorthWarriorLegs_desc_RtD", "Planted in frozen ground and holding. The magic in the metal remembers every warrior who wore these before you." },

                // Armor - Mistlands
                { "MistlandsArcherCape_RtD", "<#00A866>Archer Mistwalker Cloak" },
                { "MistlandsArcherCape_desc_RtD", "The mist hides everything equally. This cloak was made so you vanish into it before your target does." },
                { "MistlandsArcherChest_RtD", "<#00A866>Archer Mistwalker Vestment" },
                { "MistlandsArcherChest_desc_RtD", "Light enough to track something through the mist without losing breath. Durable enough for when the mist tracks you back." },
                { "MistlandsArcherHood_RtD", "<#00A866>Archer Mistwalker Hood" },
                { "MistlandsArcherHood_desc_RtD", "The Mistlands distort what you see and what sees you. This hood tilts that balance in your favor." },
                { "MistlandsArcherLegs_RtD", "<#00A866>Archer Mistwalker Legguards" },
                { "MistlandsArcherLegs_desc_RtD", "Silent in the mist, quick on wet stone. The Cursed Mistlands punishes hesitation more than it punishes fear." },
                { "MistlandsAssassinCape_RtD", "<#BE0505>Assassin Mistwalker Cloak" },
                { "MistlandsAssassinCape_desc_RtD", "The mist does half the work. This cloak does the rest. Between them nothing you hunt will hear you coming." },
                { "MistlandsAssassinChest_RtD", "<#BE0505>Assassin Mistwalker Armor" },
                { "MistlandsAssassinChest_desc_RtD", "Crafted for moving between the things that nest in the Mistlands without waking them. It has not failed yet." },
                { "MistlandsAssassinLegs_RtD", "<#BE0505>Assassin Mistwalker Pants" },
                { "MistlandsAssassinLegs_desc_RtD", "The creatures of the Cursed Mistlands hunt by sound and motion. These legs offer neither." },
                { "MistlandsAsssassinHood_RtD", "<#BE0505>Assassin Mistwalker Shroud" },
                { "MistlandsAsssassinHood_desc_RtD", "Pull it low enough and the mist accepts you as one of its own. What lives in the mist is less certain." },
                { "MistlandsMonkCape_RtD", "<#FF8645>Monk Mistwalker Cloak" },
                { "MistlandsMonkCape_desc_RtD", "Odin's Monks enter the Mistlands to seek what cannot be found in clearer places. This cloak is a declaration of that intent." },
                { "MistlandsMonkChest_RtD", "<#FF8645>Monk Mistwalker Robes" },
                { "MistlandsMonkChest_desc_RtD", "The mist parts for these robes, slightly, reluctantly, as if it recognizes the authority sewn into them." },
                { "MistlandsMonkHood_RtD", "<#FF8645>Monk Mistwalker Hood" },
                { "MistlandsMonkHood_desc_RtD", "Worn in a place where sight cannot be trusted. The Monks of the Mistlands learned to use other senses. The hood helps." },
                { "MistlandsMonkLegs_RtD", "<#FF8645>Monk Mistwalker Pants" },
                { "MistlandsMonkLegs_desc_RtD", "Steady on treacherous ground. A Monk who falls in the Mistlands is a Monk the mist keeps." },

                // Armor - Mountain
                { "MountainArcherChest_RtD", "<#00A866>Archer Frostfell Vestment" },
                { "MountainArcherChest_desc_RtD", "The Mountain offers no shelter and no mercy. This vestment was made so an archer needs neither." },
                { "MountainArcherHelmet_RtD", "<#00A866>Archer Frostfell Helm" },
                { "MountainArcherHelmet_desc_RtD", "The wind on the peaks will steal your aim if you let it. This helm was made so you do not let it." },
                { "MountainArcherLegs_RtD", "<#00A866>Archer Frostfell Pants" },
                { "MountainArcherLegs_desc_RtD", "Grip and warmth on slopes that want you to fall. The Mountain tests everyone. These help you pass." },
                { "MountainAssassinChest_RtD", "<#BE0505>Assassin Frostfell Chest" },
                { "MountainAssassinChest_desc_RtD", "White as the peak, cold as the intent behind the blade. The Cursed Mountains made camouflage and weapon indistinguishable." },
                { "MountainAssassinHood_RtD", "<#BE0505>Assassin Frostfell Hood" },
                { "MountainAssassinHood_desc_RtD", "In a blizzard every shape looks the same. This hood ensures you are the last shape anyone correctly identifies." },
                { "MountainAssassinLegs_RtD", "<#BE0505>Assassin Frostfell Legs" },
                { "MountainAssassinLegs_desc_RtD", "Soundless on ice and snow. The Mountain gives so little warning before it kills. These legs return the favor." },
                { "MountainHybridCape_RtD", "<#F0F6FF>Hybrid Frostfell Fur Cloak" },
                { "MountainHybridCape_desc_RtD", "<#F0F6FF>The Mountain does not care what kind of warrior you are. Only whether you are still standing." },
                { "MountainMonkCape_RtD", "<#FF8645>Monk Frostfell Cloak" },
                { "MountainMonkCape_desc_RtD", "Odin's Monks climb the peaks not to conquer them but to be changed by them. This cloak survives the process." },
                { "MountainMonkChest_RtD", "<#FF8645>Monk Frostfell Robes" },
                { "MountainMonkChest_desc_RtD", "The cold is a teacher the Monks respect above most others. These robes are proof of the lessons already learned." },
                { "MountainMonkHood_RtD", "<#FF8645>Monk Frostfell Hood" },
                { "MountainMonkHood_desc_RtD", "Worn where the wind carries voices that are not wind. The hood does not block them out. It helps you listen." },
                { "MountainMonkLegs_RtD", "<#FF8645>Monk Frostfell Pants" },
                { "MountainMonkLegs_desc_RtD", "Steady on ice. Odin's Monks do not fall. They have decided this, and the Mountain has not yet disagreed." },

                // Armor - Plains
                { "PlainsArcherCape_RtD", "<#00A866>Archer Lox Cloak" },
                { "PlainsArcherCape_desc_RtD", "The Plains offers no cover and no forgiveness. This cloak was made so an archer becomes the thing other things should fear finding in the open." },
                { "PlainsArcherChest_RtD", "<#00A866>Archer Lox Chestguard" },
                { "PlainsArcherChest_desc_RtD", "Lox hide hardened into something the Plains' worst cannot get through before an arrow gets to it first." },
                { "PlainsArcherHood_RtD", "<#00A866>Archer Lox Hood" },
                { "PlainsArcherHood_desc_RtD", "Low and close, keeping sun and void-wind from the eyes of someone who cannot afford to miss." },
                { "PlainsArcherLegs_RtD", "<#00A866>Archer Lox Pants" },
                { "PlainsArcherLegs_desc_RtD", "The Cursed Plains is flat and open and full of things that close distance fast. These legs were made to close it faster." },
                { "PlainsAssassinCape_RtD", "<#BE0505>Assassin Lox Cloak" },
                { "PlainsAssassinCape_desc_RtD", "The void that edges the Plains drinks light. This cloak was dyed in something that learned from it." },
                { "PlainsAssassinHood_RtD", "<#BE0505>Assassin Lox Hood" },
                { "PlainsAssassinHood_desc_RtD", "In the open flatlands, an assassin survives by becoming unremarkable. This hood is very good at unremarkable." },
                { "PlainsAssassinLegs_RtD", "<#BE0505>Assassin Lox Pants" },
                { "PlainsAssassinLegs_desc_RtD", "The Fuling patrol in patterns. These legs were made by someone who memorized every one of them." },
                { "PlainsAsssassinChest_RtD", "<#BE0505>Assassin Lox Armor" },
                { "PlainsAsssassinChest_desc_RtD", "Close-cut and void-dark. On the Plains, being seen and being dead are the same sentence." },
                { "PlainsMonkCape_RtD", "<#FF8645>Monk Lox Cloak" },
                { "PlainsMonkCape_desc_RtD", "Odin's Monks cross the Cursed Plains in silence. The void at its edges does not bother them. They have already looked into worse." },
                { "PlainsMonkChest_RtD", "<#FF8645>Monk Lox Regalia" },
                { "PlainsMonkChest_desc_RtD", "Worn under open sky by those who serve a god who watches everything and intervenes in almost nothing." },
                { "PlainsMonkHood_RtD", "<#FF8645>Monk Lox Hood" },
                { "PlainsMonkHood_desc_RtD", "The Plains wind carries whispers from the void. The Monks do not plug their ears. They learn the language." },
                { "PlainsMonkLegs_RtD", "<#FF8645>Monk Lox Pants" },
                { "PlainsMonkLegs_desc_RtD", "Steady ground or none, a Monk of the Plains walks as though both feel the same." },

                // Armor - Swamp
                { "SwampAssassinCape_RtD", "<#BE0505>Assassin Blood Cloak" },
                { "SwampAssassinCape_desc_RtD", "The Swamp swallows sound and color equally. This cloak was made to be swallowed first and leave nothing behind." },
                { "SwampAssassinChest_RtD", "<#BE0505>Assassin Blood Armor" },
                { "SwampAssassinChest_desc_RtD", "Treated against rot and worse. The Cursed Swamp does not kill cleanly. This chest ensures you do." },
                { "SwampAssassinHood_RtD", "<#BE0505>Assassin Blood Hood" },
                { "SwampAssassinHood_desc_RtD", "The bog mist hides everything. This hood hides the one thing the mist cannot — the intent behind the eyes." },
                { "SwampAssassinLegs_RtD", "<#BE0505>Assassin Blood Pants" },
                { "SwampAssassinLegs_desc_RtD", "Soundless in the mire. The dead in the Swamp never heard the one who made these coming either." },
                { "SwampMonkCape_RtD", "<#FF8645>Monk Blood Cloak" },
                { "SwampMonkCape_desc_RtD", "Odin's Monks who walk the Cursed Swamp do so with purpose. The rot parts for conviction if nothing else." },
                { "SwampMonkChest_RtD", "<#FF8645>Monk Blood Robes" },
                { "SwampMonkChest_desc_RtD", "Treated with guck and something fouler to repel what lives in the Swamp's water. What lives in its dark is a separate problem." },
                { "SwampMonkHood_RtD", "<#FF8645>Monk Blood Hood" },
                { "SwampMonkHood_desc_RtD", "The dead here are restless and the air is thick with their grievance. The hood keeps the worst of it at a distance." },
                { "SwampMonkLegs_RtD", "<#FF8645>Monk Blood Pants" },
                { "SwampMonkLegs_desc_RtD", "The creatures of the Cursed Swamp go for the ankles first. These legs were made by someone who has the scars to prove that lesson." },

                // Weapons - AshLands
                { "AshLandsAtgeir_RtD", "<#E04800>Ancient Atgeir" },
                { "AshLandsAtgeir_desc_RtD", "Reach is life in the Ashlands. This polearm gives you more of it than whatever is coming at you." },
                { "AshLandsAxe1H_RtD", "<#E04800>Ancient Axe" },
                { "AshLandsAxe1H_desc_RtD", "Ancient Metal holds an edge that normal fire cannot dull. The Ashlands has tried." },
                { "AshLandsAxe2H_RtD", "<#E04800>Ancient BattleAxe" },
                { "AshLandsAxe2H_desc_RtD", "Heavy enough to end arguments. In the Ashlands, arguments end badly for everyone involved." },
                { "AshLandsBow_RtD", "<#E04800>Ancient Bow" },
                { "AshLandsBow_desc_RtD", "Cinderwood and Ancient Metal and shadow crystal details. Everything in it was forged in fire and is entirely comfortable there." },
                { "AshLandsClub_RtD", "<#E04800>Ancient Mace" },
                { "AshLandsClub_desc_RtD", "Blunt and without apology. Ancient Metal does not need elegance to make its point." },
                { "AshLandsDagger_RtD", "<#E04800>Ancient Dagger" },
                { "AshLandsDagger_desc_RtD", "Small enough to hide and sharp enough that hiding it is worth the effort." },
                { "AshLandsDefender_RtD", "<#E04800>Ancient Defender" },
                { "AshLandsDefender_desc_RtD", "Interposed between you and something that very much wants to reach you. So far, it has been sufficient." },
                { "AshLandsShield_RtD", "<#E04800>Ancient Shield" },
                { "AshLandsShield_desc_RtD", "Ancient Metal does not buckle. Neither do the people who carry it, eventually." },
                { "AshLandsShieldBow_RtD", "<#E04800>Ancient ShieldBow" },
                { "AshLandsShieldBow_desc_RtD", "Defense and offense sharing the same frame. In the Ashlands, you do not get to choose only one." },
                { "AshLandsSledge_RtD", "<#E04800>Ancient Sledge" },
                { "AshLandsSledge_desc_RtD", "It does not cut. It ends. There is a meaningful difference and this weapon understands it perfectly." },
                { "AshLandsSpear_RtD", "<#E04800>Ancient Spear" },
                { "AshLandsSpear_desc_RtD", "Ancient Metal at the point means the first thing it touches is also the last thing it misses." },
                { "AshLandsSword1H_RtD", "<#E04800>Ancient Sword" },
                { "AshLandsSword1H_desc_RtD", "Forged in a land that does not produce anything gently. The edge reflects that upbringing." },
                { "AshLandsSword2H_RtD", "<#E04800>Ancient GreatSword" },
                { "AshLandsSword2H_desc_RtD", "Two hands, one purpose. Ancient Metal remembers every strike and does not tire of making them." },

                // Weapons - BlackForest
                { "BlackForestAtgeir_RtD", "<#FBC72A>Lightning Atgier" },
                { "BlackForestAtgeir_desc_RtD", "The storm does not ask permission. Neither does the point at the end of this." },
                { "BlackForestAxe1H_RtD", "<#FBC72A>Lightning Axe" },
                { "BlackForestAxe1H_desc_RtD", "Celestial Bronze carries the charge of the storm in its grain. Trees split faster when the lightning agrees with you." },
                { "BlackForestAxe2H_RtD", "<#FBC72A>Lightning Two-Handed Axe" },
                { "BlackForestAxe2H_desc_RtD", "Both hands, both shoulders, all of Thor's patience gone at once." },
                { "BlackForestBow_RtD", "<#FBC72A>Lightning Bow" },
                { "BlackForestBow_desc_RtD", "The arrow arrives before the sound does. The storm taught this bow everything it knows about arriving first." },
                { "BlackForestClub_RtD", "<#FBC72A>Lightning Mace" },
                { "BlackForestClub_desc_RtD", "Celestial Bronze concentrates the shock into a single point of impact. What it hits stays hit." },
                { "BlackForestDagger_RtD", "<#FBC72A>Lightning Dagger" },
                { "BlackForestDagger_desc_RtD", "Fast as the gap between lightning and thunder. In the Black Forest, that gap is all the warning anything gets." },
                { "BlackForestDefender_RtD", "<#FBC72A>Lightning Defender" },
                { "BlackForestDefender_desc_RtD", "The charge it carries makes striking it an education. Most things only need the lesson once." },
                { "BlackForestSledge_RtD", "<#FBC72A>Lightning Sledge" },
                { "BlackForestSledge_desc_RtD", "The impact lands a fraction before the thunder does. By the time the sound arrives, the fight is already decided." },
                { "BlackForestSpear_RtD", "<#FBC72A>Lightning Spear" },
                { "BlackForestSpear_desc_RtD", "Celestial Bronze at the tip means the point carries more than sharpness. It carries consequence." },
                { "BlackForestSword1H_RtD", "<#FBC72A>Lightning Sword" },
                { "BlackForestSword1H_desc_RtD", "The edge holds a charge that the blade releases on impact. The forest did not make it this way. The storm did." },
                { "BlackForestSword2H_RtD", "<#FBC72A>Lightning GreatSword" },
                { "BlackForestSword2H_desc_RtD", "Broad enough to split what the lightning does not. Between the two of them, very little is left standing." },

                // Weapons - DeepNorth
                { "DeepNorthAtgeir_RtD", "<#5218FA>Arcane Atgeir" },
                { "DeepNorthAtgeir_desc_RtD", "Frometal channeled into reach. The magic in the shaft hums at a pitch that makes the air around it hesitate." },
                { "DeepNorthAxe1H1_RtD", "<#5218FA>Arcane Axe" },
                { "DeepNorthAxe1H1_desc_RtD", "Frometal holds an edge shaped by arcane pressure rather than the whetstone. It is sharper for it, and stranger." },
                { "DeepNorthAxe1H2_RtD", "<#5218FA>Arcane Axe" },
                { "DeepNorthAxe1H2_desc_RtD", "The second variant. The runes on each axe were not cut twice the same way. The Deep North does not repeat itself." },
                { "DeepNorthAxe2H1_RtD", "<#5218FA>Arcane Greataxe" },
                { "DeepNorthAxe2H1_desc_RtD", "Heavy with Frometal and heavier with what the Deep North put inside it. Swing it and feel something ancient agree." },
                { "DeepNorthAxe2H2_RtD", "<#5218FA>Arcane War Axe" },
                { "DeepNorthAxe2H2_desc_RtD", "A war axe that has outlasted the war it was made for. The arcane in it has had time to grow patient and precise." },
                { "DeepNorthBow_RtD", "<#5218FA>Arcane Bow" },
                { "DeepNorthBow_desc_RtD", "The string does not snap in the cold of the Deep North. The magic in the limbs will not allow it." },
                { "DeepNorthClub_RtD", "<#5218FA>Arcane Mace" },
                { "DeepNorthClub_desc_RtD", "Frometal and arcane force meeting at a single point. What that point touches briefly understands something it cannot explain." },
                { "DeepNorthDagger_RtD", "<#5218FA>Arcane Dagger" },
                { "DeepNorthDagger_desc_RtD", "The edge is cold even in summer. What it cuts takes longer to heal than it should." },
                { "DeepNorthDefender_RtD", "<#5218FA>Arcane Defender" },
                { "DeepNorthDefender_desc_RtD", "The arcane in the face of this shield pushes back before you do. The Deep North made something that disagrees with being struck." },
                { "DeepNorthShield_RtD", "<#5218FA>Arcane Shield" },
                { "DeepNorthShield_desc_RtD", "Frometal does not dent the same way other metals do. It remembers the blow and redistributes it. Where it sends it is your business." },
                { "DeepNorthShieldBow_RtD", "<#5218FA>Arcane ShieldBow" },
                { "DeepNorthShieldBow_desc_RtD", "Defense and arcane reach sharing one frame. The Deep North builds things that refuse to do only one thing at a time." },
                { "DeepNorthSledge1_RtD", "<#5218FA>Arcane Sledge" },
                { "DeepNorthSledge1_desc_RtD", "The impact releases a fraction of the arcane stored in the Frometal. What it hits feels more than the weight." },
                { "DeepNorthSledge2_RtD", "<#5218FA>Arcane Sledge" },
                { "DeepNorthSledge2_desc_RtD", "A second casting of the same design. The runes differ slightly. No one from the Deep North will tell you why." },
                { "DeepNorthSpear_RtD", "<#5218FA>Arcane Spear" },
                { "DeepNorthSpear_desc_RtD", "The tip is the last thing most things from the Deep North encounter. The arcane ensures it is also the most memorable." },
                { "DeepNorthSword1H1_RtD", "<#5218FA>Arcane Sword" },
                { "DeepNorthSword1H1_desc_RtD", "Frometal holds an edge that the arcane keeps honest. It does not dull. It learns." },
                { "DeepNorthSword1H2_RtD", "<#5218FA>Arcane Sword" },
                { "DeepNorthSword1H2_desc_RtD", "The second blade. The Deep North forged two because some fights require a decision about which truth to tell." },
                { "DeepNorthSword2H1_RtD", "<#5218FA>Arcane GreatSword" },
                { "DeepNorthSword2H1_desc_RtD", "Long enough to end arguments before they reach you. The arcane in the steel agrees with that approach entirely." },
                { "DeepNorthSword2H2_RtD", "<#5218FA>Arcane GreatSword" },
                { "DeepNorthSword2H2_desc_RtD", "The second greatsword carries slightly different runes. Both cut the same. Only the memory inside them differs." },

                // Weapons - Meadows
                { "MeadowsAtgeir_RtD", "<#99C2E0>Storm Atgeir" },
                { "MeadowsAtgeir_desc_RtD", "Brass and storm-intent. The reach of this polearm was designed to keep danger at the distance the Meadows pretends it does not have." },
                { "MeadowsAxe1H_RtD", "<#99C2E0>Storm Axe" },
                { "MeadowsAxe1H_desc_RtD", "Brass does not look like much until it is swinging toward you. The storm in the grain changes that impression quickly." },
                { "MeadowsAxe2H_RtD", "<#99C2E0>Storm GreatAxe" },
                { "MeadowsAxe2H_desc_RtD", "The Meadows look peaceful. This greataxe is for the things that use that assumption against you." },
                { "MeadowsBow_RtD", "<#99C2E0>Storm Bow" },
                { "MeadowsBow_desc_RtD", "Light and fast. The storm does not linger when it strikes. Neither should you." },
                { "MeadowsClub_RtD", "<#99C2E0>Storm Mace" },
                { "MeadowsClub_desc_RtD", "Brass mace with the charge of the approaching storm in the head. Impact first. Thunder second." },
                { "MeadowsDagger_RtD", "<#99C2E0>Storm Dagger" },
                { "MeadowsDagger_desc_RtD", "Quick as lightning, close as the thing that surprised you in the soft grass. The Meadows hides its edges well." },
                { "MeadowsDefender_RtD", "<#99C2E0>Storm Defender" },
                { "MeadowsDefender_desc_RtD", "The storm in the brass pushes back. What strikes this defender strikes something that has already decided to disagree." },
                { "MeadowsSpear_RtD", "<#99C2E0>Storm Spear" },
                { "MeadowsSpear_desc_RtD", "Brass tip, storm charge, a point that arrives before whatever is behind it has finished deciding to attack." },
                { "MeadowsSword1H_RtD", "<#99C2E0>Storm Sword" },
                { "MeadowsSword1H_desc_RtD", "The Meadows does not announce its storms. This sword was made with the same philosophy." },
                { "MeadowsSword2H_RtD", "<#99C2E0>Storm GreatSword" },
                { "MeadowsSword2H_desc_RtD", "Long and charged and patient as a sky that has not broken yet. When it does, everything notices." },

                // Weapons - Mistlands
                { "MistlandsAtgeir_RtD", "<#E0ECF5>Mist Atgeir" },
                { "MistlandsAtgeir_desc_RtD", "Felmetal holds a charge the mist amplifies. The reach of this polearm is the last clear thing most targets comprehend." },
                { "MistlandsAxe1H_RtD", "<#E0ECF5>Mist Axe" },
                { "MistlandsAxe1H_desc_RtD", "Felmetal and Mistlands intention. The edge appears out of the fog before anything else does." },
                { "MistlandsAxe2H_RtD", "<#E0ECF5>Mist GreatAxe" },
                { "MistlandsAxe2H_desc_RtD", "Wide enough to clear what the mist hides. In the Mistlands, that is a considerable amount of clearing." },
                { "MistlandsBow_RtD", "<#E0ECF5>Mist Bow" },
                { "MistlandsBow_desc_RtD", "The arrow enters the mist and finds its mark anyway. Felmetal does not lose its sense of direction." },
                { "MistlandsClub_RtD", "<#E0ECF5>Mist Mace" },
                { "MistlandsClub_desc_RtD", "Heavy with Felmetal and the Mistlands' stubborn insistence that things stay broken once they are." },
                { "MistlandsDagger_RtD", "<#E0ECF5>Mist Dagger" },
                { "MistlandsDagger_desc_RtD", "It emerges from your cloak the same way things emerge from the mist — without warning and entirely committed." },
                { "MistlandsDefender_RtD", "<#E0ECF5>Mist Defender" },
                { "MistlandsDefender_desc_RtD", "Felmetal absorbs the intent behind a strike as much as the strike itself. Whatever hits this learns that the Mistlands remembers." },
                { "MistlandsSledge_RtD", "<#E0ECF5>Mist Sledge" },
                { "MistlandsSledge_desc_RtD", "It emerges from the fog and lands before anything has time to reconsider. The mist taught it that much." },
                { "MistlandsSpear_RtD", "<#E0ECF5>Mist Spear" },
                { "MistlandsSpear_desc_RtD", "The tip is the first thing that clears the mist. By the time the shaft follows, the decision has already been made." },
                { "MistlandsSword1H_RtD", "<#E0ECF5>Mist Sword" },
                { "MistlandsSword1H_desc_RtD", "Felmetal holds a quiet menace. The sword does not announce itself. It arrives." },
                { "MistlandsSword2H_RtD", "<#E0ECF5>Mist GreatSword" },
                { "MistlandsSword2H_desc_RtD", "Long enough that the mist parts for the blade before anything sees the warrior behind it." },

                // Weapons - Mountain
                { "MountainAtgeir_RtD", "<#76A5AF>Ice Atgeir" },
                { "MountainAtgeir_desc_RtD", "QuickSilver keeps the cold of the peak in the shaft. Reach that freezes on contact is not a negotiating position." },
                { "MountainAxe1H_RtD", "<#76A5AF>Ice Axe" },
                { "MountainAxe1H_desc_RtD", "QuickSilver does not warm. The axe carries that refusal into every swing." },
                { "MountainAxe2H_RtD", "<#76A5AF>Ice Battleaxe" },
                { "MountainAxe2H_desc_RtD", "Two hands on something that has never once agreed to be warm. The Mountain is proud of this." },
                { "MountainBow_RtD", "<#76A5AF>Ice Bow" },
                { "MountainBow_desc_RtD", "The string does not flex in the cold — it sharpens. Every shot carries the Mountain's indifference with it." },
                { "MountainClub_RtD", "<#76A5AF>Ice Mace" },
                { "MountainClub_desc_RtD", "QuickSilver and impact and cold. What it strikes is left with all three, whether it wanted any of them." },
                { "MountainDagger_RtD", "<#76A5AF>Ice Dagger" },
                { "MountainDagger_desc_RtD", "The blade stays cold even held in a warm fist. What it opens does not close the way it should." },
                { "MountainDefender_RtD", "<#76A5AF>Ice Defender" },
                { "MountainDefender_desc_RtD", "Striking it is like striking the Mountain itself — cold, indifferent, and entirely unimpressed." },
                { "MountainSledge_RtD", "<#76A5AF>Ice Sledge" },
                { "MountainSledge_desc_RtD", "The cold concentrates in the head and releases on impact. What it hits briefly understands what the peak feels like from the inside." },
                { "MountainSpear_RtD", "<#76A5AF>Ice Spear" },
                { "MountainSpear_desc_RtD", "A point of QuickSilver cold moving faster than the wind that made it. The Mountain trained this spear well." },
                { "MountainSword1H_RtD", "<#76A5AF>Ice Sword" },
                { "MountainSword1H_desc_RtD", "The edge stays sharp in temperatures that ruin other metals. The cold is not its enemy. It is its maker." },
                { "MountainSword2H_RtD", "<#76A5AF>Ice GreatSword" },
                { "MountainSword2H_desc_RtD", "Long enough to reach what the blizzard hides. Cold enough to remind it why hiding was the right instinct." },

                // Weapons - Plains
                { "PlainsAtgeir_RtD", "<#AA08D0>Void Atgeir" },
                { "PlainsAtgeir_desc_RtD", "Netherite at the point and void-dark along the shaft. The reach of this polearm borrows from a darkness that does not give things back." },
                { "PlainsAxe1H_RtD", "<#AA08D0>Void Axe" },
                { "PlainsAxe1H_desc_RtD", "Netherite does not reflect light. The axe head drinks it instead and uses what it finds." },
                { "PlainsAxe2H_RtD", "<#AA08D0>Void Greataxe" },
                { "PlainsAxe2H_desc_RtD", "The void does not swing. This greataxe does it on the void's behalf." },
                { "PlainsBow_RtD", "<#AA08D0>Void Warbow" },
                { "PlainsBow_desc_RtD", "A war bow drawn from Netherite and void-intent. The arrow does not merely travel. It is dispatched." },
                { "PlainsClub_RtD", "<#AA08D0>Void Mace" },
                { "PlainsClub_desc_RtD", "The weight of Netherite and the gravity of the void it came from. Impact that echoes in ways sound cannot account for." },
                { "PlainsDagger_RtD", "<#AA08D0>Void Dagger" },
                { "PlainsDagger_desc_RtD", "Small and void-dark and patient. The Plains' assassins do not hurry. This dagger learned from them." },
                { "PlainsDefender_RtD", "<#AA08D0>Void Defender" },
                { "PlainsDefender_desc_RtD", "The void behind this shield pulls at whatever strikes it. Most things prefer to stop before finding out how hard." },
                { "PlainsSledge_RtD", "<#AA08D0>Void Sledge" },
                { "PlainsSledge_desc_RtD", "Netherite heavy with void pressure. What it hits briefly experiences the weight of everything the Plains decided to forget." },
                { "PlainsSpear_RtD", "<#AA08D0>Void Spear" },
                { "PlainsSpear_desc_RtD", "The point opens something. Not just flesh. The void has opinions about what lies beyond it, and the spear carries them." },
                { "PlainsSword1H_RtD", "<#AA08D0>Void Sword" },
                { "PlainsSword1H_desc_RtD", "The edge absorbs light along the blade. What cannot be seen cannot be avoided. The Plains learned this early." },
                { "PlainsSword2H_RtD", "<#AA08D0>Void GreatSword" },
                { "PlainsSword2H_desc_RtD", "Long and void-forged and carrying the patience of a darkness that has been waiting longer than the blade has existed." },

                // Weapons - Swamp
                { "SwampAtgeir_RtD", "<#CAE2C2>Earth Atgeir" },
                { "SwampAtgeir_desc_RtD", "BrightSteel and bog-intent. The reach of this polearm was designed by someone who knew how close the Swamp's worst prefers to get." },
                { "SwampAxe1H_RtD", "<#CAE2C2>Earth Axe" },
                { "SwampAxe1H_desc_RtD", "BrightSteel does not rust in the Swamp's damp. It was forged to outlast the wet and the rot and everything they carry." },
                { "SwampAxe2H_RtD", "<#CAE2C2>Earth GreatAxe" },
                { "SwampAxe2H_desc_RtD", "Wide enough to clear the undergrowth and the things hiding in it. The Swamp grows back. This axe does not care." },
                { "SwampBow_RtD", "<#CAE2C2>Earth Bow" },
                { "SwampBow_desc_RtD", "BrightSteel limbs that do not warp in the wet. The Swamp tries to ruin everything it touches. This bow declined." },
                { "SwampClub_RtD", "<#CAE2C2>Earth Mace" },
                { "SwampClub_desc_RtD", "BrightSteel and the weight of the deep earth behind every swing. The bog knows this sound. It does not like what follows." },
                { "SwampDagger_RtD", "<#CAE2C2>Earth Dagger" },
                { "SwampDagger_desc_RtD", "Short and certain. In the Swamp's close quarters, a long blade is a disadvantage and a sharp one is everything." },
                { "SwampDefender_RtD", "<#CAE2C2>Earth Defender" },
                { "SwampDefender_desc_RtD", "BrightSteel forged with the stubbornness of the earth it came from. What the Swamp sends against it finds something that refuses to yield." },
                { "SwampSledge_RtD", "<#CAE2C2>Earth Sledge" },
                { "SwampSledge_desc_RtD", "The deep earth remembers every blow. This sledge returns a fraction of that memory to whatever it strikes." },
                { "SwampSpear_RtD", "<#CAE2C2>Earth Spear" },
                { "SwampSpear_desc_RtD", "BrightSteel tip and the reach to keep the Swamp's worst at a distance it finds frustrating." },
                { "SwampSword1H_RtD", "<#CAE2C2>Earth Sword" },
                { "SwampSword1H_desc_RtD", "The edge holds through the damp and the dark. BrightSteel was made for exactly this kind of persistence." },
                { "SwampSword2H_RtD", "<#CAE2C2>Earth GreatSword" },
                { "SwampSword2H_desc_RtD", "Long and BrightSteel-bright in the Swamp's perpetual dark. Everything in the bog knows what that light means." },
                
                // Special Weapons
                { "OdinsDefender_RtD", "<#933D41>Odins Defender" },
                { "OdinsDefender_desc_RtD", "Odin built this to guard what he values. The fact that you carry it means either you earned it or he is testing you. Possibly both." },
                { "OdinsFist_RtD", "<#933D41>Odins Fist" },
                { "OdinsFist_desc_RtD", "It grows heavier with each soul it has touched. Odin calls that strength. The souls might call it something else." },
                { "AxeFlametal_RtD", "Flametal WoodCutting Axe" },
                { "AxeFlametal_desc_RtD", "The finest axe available for felling. Trees that have survived centuries do not survive this." },
                { "PickAxeFlametal_RtD", "Flametal Mining Axe" },
                { "PickAxeFlametal_desc_RtD", "It breaks what lesser picks cannot find. The earth gives up its secrets when it has no remaining choice." },

                // Status Effects - Archer
                { "SE_ArcherAshLands_RtD", "Ember Draw" },
                { "SE_ArcherAshLands_desc_RtD", "The heat of South Alfheimr is in the bow arm now. Every shot carries the Ashlands' anger with it." },
                { "SE_ArcherBlackForest_RtD", "Root Sight" },
                { "SE_ArcherBlackForest_desc_RtD", "The forest shows you the gaps between the dark. Your arrows find them before your eyes do." },
                { "SE_ArcherDeepNorth_RtD", "Arcane Aim" },
                { "SE_ArcherDeepNorth_desc_RtD", "The Deep North sharpens intention. Every shot is guided by something colder and more precise than instinct." },
                { "SE_ArcherMistlands_RtD", "Veil Pierce" },
                { "SE_ArcherMistlands_desc_RtD", "The mist parts for your arrows. What hides within it has no more cover than what stands in the open." },
                { "SE_ArcherMountain_RtD", "Frost Nock" },
                { "SE_ArcherMountain_desc_RtD", "The cold steadies the hand and focuses the eye. The Mountain gives nothing freely. This it lends." },
                { "SE_ArcherPlains_RtD", "Void Flight" },
                { "SE_ArcherPlains_desc_RtD", "Your arrows cross the open Plains like something the void sent ahead of itself. Nothing outpaces them." },
                { "SE_ArcherSwamp_RtD", "Bog Mark" },
                { "SE_ArcherSwamp_desc_RtD", "The Swamp teaches patience before it teaches anything else. Your aim is the better for the lesson." },

                // Status Effects - Assassin
                { "SE_AssassinAshLands_RtD", "Cinder Step" },
                { "SE_AssassinAshLands_desc_RtD", "You move through the Ashlands heat like something born in it. The fire notices. It lets you pass." },
                { "SE_AssassinBlackForest_RtD", "Shadow Bark" },
                { "SE_AssassinBlackForest_desc_RtD", "The forest has decided you are one of its shadows. What hunts in the dark between the pines does not see you as prey." },
                { "SE_AssassinDeepNorth_RtD", "Pale Step" },
                { "SE_AssassinDeepNorth_desc_RtD", "You move across the ice of North Alfheimr without sound and nearly without presence. The cold approves of your discretion." },
                { "SE_AssassinMistlands_RtD", "Shroud Walk" },
                { "SE_AssassinMistlands_desc_RtD", "The mist has accepted you. What lives within it does not distinguish you from the fog itself. Use that carefully." },
                { "SE_AssassinMountain_RtD", "Frost Veil" },
                { "SE_AssassinMountain_desc_RtD", "The blizzard hides you as completely as it hides everything else. The difference is you chose to be here." },
                { "SE_AssassinPlains_RtD", "Void Shroud" },
                { "SE_AssassinPlains_desc_RtD", "The void at the edge of the Plains lends its darkness. You wear it and the open flatlands offers no more cover to your enemies than to you." },
                { "SE_AssassinSwamp_RtD", "Bog Silence" },
                { "SE_AssassinSwamp_desc_RtD", "The Swamp swallows sound. You have learned to swallow it faster. What you hunt hears nothing before it hears nothing ever again." },

                // Status Effects - Monk
                { "SE_MonkArmorAshLands_RtD", "Ember Devotion" },
                { "SE_MonkArmorAshLands_desc_RtD", "Odin's fire burns in you as well as around you. In South Alfheimr, faith and flame are the same discipline." },
                { "SE_MonkArmorBlackForest_RtD", "Root Vigil" },
                { "SE_MonkArmorBlackForest_desc_RtD", "The Cursed Forest tests everyone who walks it. Odin's Monks walk it twice and return changed both times." },
                { "SE_MonkArmorDeepNorth_RtD", "Arcane Vigil" },
                { "SE_MonkArmorDeepNorth_desc_RtD", "Something ancient has noticed you. It is not alarmed. That should alarm you." },
                { "SE_MonkArmorMistlands_RtD", "Veilborn Clarity" },
                { "SE_MonkArmorMistlands_desc_RtD", "The mist does not confuse you the way it confuses others. Odin's Monks in the Mistlands learned to think in fog." },
                { "SE_MonkArmorMountain_RtD", "Frost Communion" },
                { "SE_MonkArmorMountain_desc_RtD", "The cold is a teacher the Monks respect above most others. This is the mark of a lesson already internalized." },
                { "SE_MonkArmorPlains_RtD", "Void Mantle" },
                { "SE_MonkArmorPlains_desc_RtD", "The void has wrapped itself around you. You are not protected. You are claimed." },
                { "SE_MonkArmorSwamp_RtD", "Bog Pact" },
                { "SE_MonkArmorSwamp_desc_RtD", "The rot has accepted you as one of its own. Whether that is a blessing depends entirely on your perspective." },

                // Status Effects - Warrior
                { "SE_WarriorArmorAshLands_RtD", "Ember Fury" },
                { "SE_WarriorArmorAshLands_desc_RtD", "The Ashlands does not make patient warriors. It makes effective ones. You have become both." },
                { "SE_WarriorArmorBlacKForest_RtD", "Root Wrath" },
                { "SE_WarriorArmorBlacKForest_desc_RtD", "The Black Forest's curse runs through you now. Whatever it feared in the dark, you have become." },
                { "SE_WarriorArmorDeepNorth_RtD", "Arcane Endurance" },
                { "SE_WarriorArmorDeepNorth_desc_RtD", "The Deep North does not break warriors. It reveals which ones were never going to break." },
                { "SE_WarriorArmorMistlands_RtD", "Veil Resolve" },
                { "SE_WarriorArmorMistlands_desc_RtD", "You have walked the Cursed Mistlands and returned with more than you came with. The mist does not like to be owed." },
                { "SE_WarriorArmorMountain_RtD", "Frost Bastion" },
                { "SE_WarriorArmorMountain_desc_RtD", "The Mountain tested you and found you sufficient. It will not say so aloud. This is as close as it comes." },
                { "SE_WarriorArmorPlains_RtD", "Void Bulwark" },
                { "SE_WarriorArmorPlains_desc_RtD", "You stand on ground that borders nothing and call it home. The void respects that kind of audacity." },
                { "SE_WarriorArmorSwamp_RtD", "Bog Resilience" },
                { "SE_WarriorArmorSwamp_desc_RtD", "The Swamp tried everything it had. You are still here. It has made a note of that." },

                // Status Effects - Other
                { "SE_DeerHideMeadows_RtD", "Survivor's Mark" },
                { "SE_DeerHideMeadows_desc_RtD", "The Meadows was supposed to be the easy part. You are still here, which means you already know it was not." },
                { "SE_OdinsFists_RtD", "Odin's Blessing" },
                { "SE_OdinsFists_desc_RtD", "The Allfather's strength moves through your hands. Whether he gave it or you took it is between you and him." },

                // Forge Extensions
                { "forge_ext7_RtD", "Odin's Anvil" },
                { "forge_ext7_desc_RtD", "Blessed by the Allfather. What is shaped here carries his intention, whether you intended that or not." },
                { "forge_ext8_RtD", "Odin's Cooler" },
                { "forge_ext8_desc_RtD", "The metal cools faster here than it should. Odin does not believe in waiting longer than necessary." },
                { "forge_ext9_RtD", "Odin's Tools" },
                { "forge_ext9_desc_RtD", "Touched by a god who has broken and remade more things than you will ever count. The tools remember all of it." },
                { "forge_ext10_RtD", "Odin's Anvils" },
                { "forge_ext10_desc_RtD", "A second set, blessed twice. The Allfather values redundancy in the things he cannot afford to lose." },
                { "forge_ext11_RtD", "Odin's Wheel" },
                { "forge_ext11_desc_RtD", "It turns without being turned. Odin built something into it that has not stopped moving since." },

                // Shields
                { "MeadowsShield_RtD", "<#E04800>Storm Shield" },
                { "MeadowsShield_desc_RtD", "The storm that gave this shield its name is still in it. What strikes it strikes the weather first." },
                { "BlackForestShield_RtD", "<#E04800>Celestial Shield" },
                { "BlackForestShield_desc_RtD", "Forged from Celestial Bronze and the Black Forest's stubbornness. It has not yielded yet and has no plans to start." },
                { "SwampShield_RtD", "<#E04800>Moon Shield" },
                { "SwampShield_desc_RtD", "MoonIron holds the Swamp's dim light in its face. What attacks from the dark sees itself reflected just before it connects." },
                { "MountainShield_RtD", "<#E04800>Silverlight Shield" },
                { "MountainShield_desc_RtD", "Cold to the grip and harder than the peak it came from. The Mountain built this to outlast everything that strikes it." },
                { "PlainsShield_RtD", "<#E04800>Void Shield" },
                { "PlainsShield_desc_RtD", "The void in the face of this shield absorbs the intent behind a blow before it absorbs the blow itself." },
                { "MistlandsShield_RtD", "<#E04800>Elemental Shield" },
                { "MistlandsShield_desc_RtD", "Felmetal and Mistlands intention. The mist still clings to the edges. What it hides there is your advantage." },
            });
        }
    }
}